// utils/selectors.ts
export const selectors = {
  email: '#email',
  password: '#password',
  submitButton: 'button[type="submit"]',
  emailError: '#email-helper-text',
  passwordError: '#password-helper-text',
  errorMessage: 'div.MuiAlert-message.css-1pxa9xg-MuiAlert-message',
  togglePasswordButton: 'button.MuiButtonBase-root.MuiIconButton-root',
  walletLink: 'div#root>div>div>a:nth-of-type(3)',
  withdrawText: 'text=Withdraw',
  fundWalletText: 'text=Fund wallet',
  transferText: 'text=Transfer',
  walletBalance: 'p.mt-3.font-tomato',
  toggleButton: 'button.text-primary',
  walletHidden: 'text=******',
  plansLink: 'div#root>div>div>a:nth-of-type(2)',
  noPlansMessage: 'text=You have not created any plans. Click on any of the cards below to create a plan',
  existingPlans: "a[data-test-id='user-plan']",
  buildWealthPlanCard: 'a._buildWealthPlanCard_1rcc3_32._planCard_1rcc3_1',
  startInvestingButton: 'button:has-text("start investing")',
  nigerianNairaOption: 'text=Nigerian Naira',
  nameInput: '#name',
  continueButton: 'button:has-text("continue")',
  savingsInput: 'input[name="savings"]',
  retirementAgeWarning: 'text=Retirement Age should be greater than your current age',
  preferencesText: 'text=Preferences',
  yourPortfolioText: 'text=Your Portfolio',
  projectionText: 'text=Projection',
  agreeAndContinueButton: 'button:has-text("agree & continue")',
  reviewText: 'text=Review',
  createPlanButton: 'button:has-text("create plan")',
  buildWealthPlanCreatedText: 'text=You just created your Build Wealth plan'
};
